<h1>Анализатор калорийности продуктов</h1>

<?php
$message = $this->get('session')->message();
if($message){
    echo '<div class="text-center alert alert-danger" role="alert">'.$message.'</div>';
}
?>

<style>
    #analyzer_table{font-size:14px; border:1px solid #ccc; margin:1em 0;
        padding: 0;
        /*width: 100%;*/
        border-collapse: collapse;
        border-spacing: 0;

    }
    #analyzer_table tr td{border: 1px solid #ccc; padding:2px 5px; font-weight:bold;}
    .t_h td{text-align:center; background-color:#ccffcb; color:#00a000;}
    .t_f td{text-align:right; background-color:#ccffcb; color:#00a000;}
    .t_b td{text-align:right; color:#777;}
    #analyzer_table .input_name{height:20px; width:300px; color:#777; margin:0 -3px;}
    #analyzer_table .input_number{height:20px; width:80px; color:#777; text-align:right; margin:0 -3px;}


</style>

<form method="post">
    <table id="analyzer_table">
        <tr class="t_h">
            <td>№</td>
            <td>Продукт</td>
            <td>Вес, гр</td>
            <td>Бел, гр</td>
            <td>Жир, гр</td>
            <td>Угл, гр</td>
            <td>Кал, ккал</td>
        </tr>

        <?php foreach($result as $number=>$tab) : ?>
            <tr class="t_b">
                <td style="text-align:center;"><?=$number?></td>
                <td style="text-align:left;">
                    <input name="name_<?=$number?>" class="input_name" value="<?=$tab->name?>">
                </td>
                <td>
                    <input name="weight_<?=$number?>" class="input_number" value="<?=$tab->weight?>">
                </td>
                <td style="text-align:right;"><?=$tab->proteins?></td>
                <td style="text-align:right;"><?=$tab->fats?></td>
                <td style="text-align:right;"><?=$tab->carbohydrates?></td>
                <td style="text-align:right;"><?=$tab->calories?></td>
            </tr>
        <?php endforeach?>

        <tr class="t_f">
            <td></td>
            <td style="text-align: left;">Итого:</td>
            <td><?=$sum->weight?></td>
            <td><?=$sum->proteins?></td>
            <td><?=$sum->fats?></td>
            <td><?=$sum->carbohydrates?></td>
            <td><?=$sum->calories?></td>
        </tr>
        <tr class="t_f">
            <td></td>
            <td style="text-align: left;">Итого на 100 грамм:</td>
            <td>100.00</td>
            <td>100.00</td>
            <td>100.00</td>
            <td>100.00</td>
            <td>100.00</td>
        </tr>
    </table>

    <button name="key" value="analyze">Вичислить</button>
    <button name="key" value="new">Добавить новый продукт</button>

</form>


<form method="post">
    <table id="analyzer_table">
        <tr class="t_h">
            <td>№</td>
            <td>Продукт</td>
            <td>Вес, гр</td>
            <td>Бел, гр</td>
            <td>Жир, гр</td>
            <td>Угл, гр</td>
            <td>Кал, ккал</td>
        </tr>
        <tr class="t_b">
            <td style="text-align:center;">1</td>
            <td style="text-align:left;"><input name="name" class="input_name"></td>
            <td style="text-align:right;">100.00</td>
            <td style="text-align:right;"><input name="proteins" class="input_number"></td>
            <td style="text-align:right;"><input name="fats" class="input_number"></td>
            <td style="text-align:right;"><input name="carbohydrates" class="input_number"></td>
            <td style="text-align:right;"><input name="calories" class="input_number"></td>
        </tr>
    </table>
    <button name="key" value="add">Добавить в базу</button>
</form>