<h2 class="sub-header">Section title</h2>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>id</th>
            <th>title</th>
            <th>description</th>
            <th>price</th>
            <th>status</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($books as $book):?>
            <tr>
                <td><?=$book->id?></td>
                <td><?=$book->title?></td>
                <td><?=$book->description?></td>
                <td><?=$book->price?></td>
                <td><?=($book->status)?"Yes":"No"?></td>
            </tr>
        <?php endforeach?>
        </tbody>
    </table>
</div>