<h2 class="sub-header">
    Books
    <a href="<?=$this->get('router')->getUrl("admin_book_add")?>" class="btn btn-primary">Добавить книгу</a>
    <a href="<?=$this->get('router')->getUrl('admin_book_style')?>" class="btn btn-primary">Style</a>
</h2>

<div class="table-responsive" style="min-height:400px;">
    <table class="table table-striped">
        <thead>
        <tr>
            <th style="width:50px;">
                <a <?=($sorting->sort_id==1?'class="dropup"':"")?> href="<?=$this->get('router')->getUrl('admin_books_sorting',['sort'=>'id','param'=>$sorting->sort_id+1])?>" style="color:#000;">
                    Id<?php if($sorting->sort_id):?><span class="caret"></span><?php endif?>
                </a>
            </th>

            <th>
                <a <?=($sorting->sort_title==1?'class="dropup"':"")?> href="<?=$this->get('router')->getUrl('admin_books_sorting',['sort'=>'title','param'=>$sorting->sort_title+1])?>" style="color:#000;">
                    Title<?php if($sorting->sort_title):?><span class="caret"></span><?php endif?>
                </a>
            </th>
            <th style="width:80px;">
                <a <?=($sorting->sort_price==1?'class="dropup"':"")?> href="<?=$this->get('router')->getUrl('admin_books_sorting',['sort'=>'price','param'=>$sorting->sort_price+1])?>" style="color:#000;">
                    Price<?php if($sorting->sort_price):?><span class="caret"></span><?php endif?>
                </a>
            </th>

            <th class="dropdown" style="width:100px">
                <a style="color:#000;" data-toggle="dropdown">
                    Style<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a <?=($sorting->sort_style==0?'style="color:#777; background:#f7f7f7;"':'href="'.$this->get('router')->getUrl('admin_books_sorting',['sort'=>'style','param'=>0]).'"')?> >---</a></li>
                    <?php foreach($styles as $style):?>
                        <?php if($sorting->sort_style==$style->id):?>
                            <li><a style="color:#777; background:#f7f7f7;"><?=$style->title?></a></li>
                        <?php else:?>
                            <li><a href="<?=$this->get('router')->getUrl('admin_books_sorting',['sort'=>'style','param'=>$style->id])?>"><?=$style->title?></a></li>
                        <?php endif?>
                    <?php endforeach?>
                </ul>
            </th>

            <th style="width:70px;">
                <a href="<?=$this->get('router')->getUrl('admin_books_sorting',['sort'=>'status','param'=>$sorting->sort_status+1])?>" style="color:#000;">
                    Status<?php if($sorting->sort_status==1):?><small>+</small><?php elseif($sorting->sort_status==2):?>-<?php endif?>
                </a>
            </th>

            <th style="width:100px">Setting</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($books as $book):?>
            <tr>
                <td><?=$book->id?></td>
                <td><?=$book->title?></td>
                <td><?=$book->price?></td>
                <td><?=$book->style?></td>
                <td><?=($book->status)?"Yes":"No"?></td>
                <td>
                    <a href="<?=$this->get('router')->getUrl('admin_book_edit',["id"=>$book->id])?>" class="btn btn-success btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a href="<?=$this->get('router')->getUrl('admin_book_delete',["id"=>$book->id])?>" class="btn btn-danger btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach?>
        </tbody>
    </table>
</div>