<h2 class="sub-header">Books <a href="<?=$this->get('router')->getUrl("admin_book_add")?>" class="btn btn-primary">Добавить</a></h2>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Price</th>
            <th>Style</th>
            <th>Status</th>
            <th>Setting</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($books as $book):?>
            <tr>
                <td><?=$book->id?></td>
                <td><?=$book->title?></td>
                <td style="width:100px"><?=$book->price?></td>
                <td style="width:100px"><?=$book->style?></td>
                <td style="width:50px"><?=($book->status)?"Yes":"No"?></td>
                <td style="width:100px">
                    <a href="<?=$this->get('router')->getUrl('admin_book_edit',["id"=>$book->id])?>" class="btn btn-success">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a href="<?=$this->get('router')->getUrl('admin_book_delete',["id"=>$book->id])?>" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach?>
        </tbody>
    </table>
</div>