<?php
    $message = $this->get('session')->message();
    if($message){
        echo '<div class="text-center alert alert-danger" role="alert">'.$message.'</div>';
    }
?>

<form class="form-signin" method="post">
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" name="email" id="inputEmail" class="form-control input-first" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control input-last" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="yes"> Remember me
            </label>
        </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
