<?php
$message = $this->get('session')->message();
if($message){
    echo '<div class="text-center alert alert-danger" role="alert">'.$message.'</div>';
}
?>

<form class="form-signin" method="post">
    <h2 class="form-signin-heading">Регистрация</h2>
    <label for="inputUserName" class="sr-only">User name</label>
    <input value="<?=$form->username?>" type="text" name="username" id="inputUserName" class="form-control input-first" placeholder="User name" required autofocus>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input  value="<?=$form->email?>" type="email" name="email" id="inputEmail" class="form-control input" placeholder="Email address" required>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control input" placeholder="Password" required>
    <label for="inputPasswordConfirm" class="sr-only">Password Confirm</label>
    <input type="password" name="passwordConfirm" id="inputPasswordConfirm" class="form-control input-last" placeholder="Password Confirm" required>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="active" value="yes"> Согласен с <a>правилами сайта</a>
                </label>
            </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
</form>