<div class="page-header">
    <h2><?=$book->title?></h2>
</div>

<ol class="breadcrumb">
    <li><a href="<?=$this->get('router')->getUrl("home_")?>">Главная</a></li>
    <li><a href="<?=$this->get('router')->getUrl("books")?>">Книги</a></li>
    <li class="active"><?=$book->title?></li>
</ol>

<div class="row">
    <div class="col-lg-3">
        <img data-src="holder.js/300x200" alt="..." src="/img/small.jpg">
    </div>
    <div class="col-lg-9">
        <h2><?=$book->title?></h2>
        <h4>
            <?=$book->price?>$
            <a class="btn btn-primary" onclick="addCart('<?=$this->get('router')->getUrl('api_cart_add',['id'=>$book->id])?>')">Добавить в корзину</a>
        </h4>

        <p><?=$book->description?></p>
    </div>
</div>


