
<div class="page-header">
    <h1>Books</h1>
</div>

<ol class="breadcrumb">
    <li><a href="<?=$this->get('router')->getUrl("home_")?>">Главная</a></li>
    <?php if(is_object($category)):?>
        <li><a href="<?=$this->get('router')->getUrl('books')?>">Книги</a></li>
        <li class="active"><?=$category->name?></li>
    <?php else:?>
        <li class="active">Книги</li>
    <?php endif?>
</ol>

<div class="text-center">



    <div class="row">

        <div class="col-lg-2">
            <div class="list-group">
                <?php foreach($style as $item):?>
                    <a href="<?=$item->url?>" class="list-group-item <?=($item->active?'active':'')?>"><?=$item->name?></a>
                <?php endforeach?>
            </div>
        </div>

        <div class="col-lg-9">

            <?php foreach($books as $book):?>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="thumbnail div400">
                        <div class="img_size300x200">
                            <img data-src="holder.js/300x200" alt="..." src="/img/small.jpg">
                        </div>
                        <div class="caption">
                            <h3><?=$book->title?></h3>
                            <p class="p_size40"><?=$book->price?>$</p>
                            <p>
                                <a href="<?=$this->get('router')->getUrl("book_show",['id'=>$book->id])?>" class="btn btn-primary" role="button">Show</a>
                                <a onclick="addCart('<?=$this->get('router')->getUrl('api_cart_add',['id'=>$book->id])?>')" class="btn btn-default" role="button">Add to cart</a>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>

        </div>

    </div>

    <ul class="pagination">
        <?foreach($buttons as $button):?>
            <li <?php
            if($button->active) : echo 'class="active"';
            elseif($button->disabled) : echo 'class="disabled"';
            else : echo '';
            endif;
            ?> >
                <?php if(!$button->active and !$button->disabled) : ?>
                    <a href="<?=$button->url?>">
                        <?=$button->text?>
                    </a>
                <?php else :?>
                    <span><?=$button->text?></span>
                <?php endif ?>
            </li>
        <?endforeach;?>
    </ul>
</div><!-- .text-center -->

