<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/ico/favicon.ico">

    <title>My MVC</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/starter-template.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/sticky-footer-navbar.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/signin.css" rel="stylesheet">

</head>

<body>

<div class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">My MVC</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach($this->get('router')->navBar(['Главная'=>"home_","Книги"=>"books",'Корзина <span id="cart" class="badge">'.$this->cart->amount().'</span>'=>'cart'],true) as $button):?>
                    <li <?=($button->active?'class="active"':'')?> ><a href="<?=$button->url?>"><?=$button->name?></a></li>
                <?php endforeach?>
            </ul>

<!--            <form class="navbar-form navbar-right">-->
<!--                <input type="text" class="form-control" placeholder="Search...">-->
<!--            </form>-->
            <div class="navbar-btn navbar-right">
                <?php if($this->get('session')->hash('user_session')): ?>
                    <a class="btn btn-primary"><?=$this->get('session')->get('user_session')?></a>
                    <a class="btn btn-danger" href="<?=$this->get('router')->getUrl('logout')?>">Выйти</a>
                <?php elseif($this->cookie->test('login')):?>
                    <a class="btn btn-primary"><?=$this->cookie->get('login')?></a>
                    <a class="btn btn-danger" href="<?=$this->get('router')->getUrl('logout')?>">Выйти</a>
                <?php else:?>
                    <a class="btn btn-success" href="<?=$this->get('router')->getUrl('register')?>">Регистрация</a>
                    <a class="btn btn-primary" href="<?=$this->get('router')->getUrl('login')?>">Войти</a>
                <?php endif;?>
            </div>





<!--            <form class="navbar-form navbar-right">-->
<!--                <div class="form-group">-->
<!--                    <input type="text" placeholder="Email" class="form-control">-->
<!--                </div>-->
<!--                <div class="form-group">-->
<!--                    <input type="password" placeholder="Password" class="form-control">-->
<!--                </div>-->
<!--                <button type="submit" class="btn btn-success">Sign in</button>-->
<!--            </form>-->


        </div><!--/.nav-collapse -->

    </div>
</div>


<div class="container">

    <?=$_content;?>

</div><!-- /.container -->

<footer class="footer">
    <div class="container container-footer">
<!--        <p class="text-muted">Place sticky footer content here.</p>-->
<!--        <a href="http://corp.wamba.com/ru/test/"><img border="0" src="http://corp.wamba.com/ru/test/widget/?id=147188" /></a>-->
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/my_js.js"></script>
</body>
</html>
